The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [40]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Start coding here!
nobel_list = pd.read_csv('data/nobel.csv')
nobel_list.head(20)

    year    category  ...      death_city   death_country
0   1901   Chemistry  ...          Berlin         Germany
1   1901  Literature  ...        Châtenay          France
2   1901    Medicine  ...         Marburg         Germany
3   1901       Peace  ...          Heiden     Switzerland
4   1901       Peace  ...           Paris          France
5   1901     Physics  ...          Munich         Germany
6   1902   Chemistry  ...          Berlin         Germany
7   1902  Literature  ...  Charlottenburg         Germany
8   1902    Medicine  ...    Putney Heath  United Kingdom
9   1902       Peace  ...            Bern     Switzerland
10  1902       Peace  ...            Bern     Switzerland
11  1902     Physics  ...             NaN     Netherlands
12  1902     Physics  ...       Amsterdam     Netherlands
13  1903   Chemistry  ...       Stockholm          Sweden
14  1903  Literature  ...           Paris          France
15  1903    Medicine  ...      Copenhagen         Denmark
16  1903       Peace  ...          London  United Kingdom
17  1903     Physics  ...             NaN          France
18  1903     Physics  ...           Paris          France
19  1903     Physics  ...      Sallanches          France

[20 rows x 18 columns]

In [41]:
top_gender_list = nobel_list.groupby("sex").size().sort_values(ascending=False)
print("Ganadores por Sexo (descendente por conteo):")
print(top_gender_list)
top_gender = str(top_gender_list.head(1).index[0])
top_country_list = nobel_list.groupby("birth_country").size().sort_values(ascending=False)
print(top_country_list)
top_country = str(top_country_list.head(1).index[0])
print("Which gender won most Nobel Prices:")
print(top_gender)
print("Which country won most Nobel Prices")
print(top_country)

Ganadores por Sexo (descendente por conteo):
sex
Male      905
Female     65
dtype: int64
birth_country
United States of America                        291
United Kingdom                                   91
Germany                                          67
France                                           58
Sweden                                           30
                                               ...
French protectorate of Tunisia (now Tunisia)      1
Free City of Danzig (Poland)                      1
Faroe Islands (Denmark)                           1
Ethiopia                                          1
Yemen                                             1
Length: 129, dtype: int64
Which gender won most Nobel Prices:
Male
Which country won most Nobel Prices
United States of America

In [42]:
import numpy as np

# Calculate the decade for each Nobel prize
nobel_list['decade'] = np.floor(nobel_list['year'] / 10) * 10

# Filter the list for winners from the United States
us_winers = nobel_list[nobel_list['birth_country'] == 'United States of America'].copy()

# Calculate the decade for US winners
us_winers['decade'] = np.floor(us_winers['year'] / 10) * 10

# Count the number of US winners per decade
us_decade_count = us_winers.groupby('decade').size().reset_index(name='us_winners_count')

# Count the total number of winners per decade
total_winners_per_decade = nobel_list.groupby('decade').size().reset_index(name='total_winners')

# Merge the US winners count with the total winners count
us_decade_count = us_decade_count.merge(total_winners_per_decade, on='decade')

# Display the first 15 rows of the result
us_decade_count['ratio'] = us_decade_count['us_winners_count']/us_decade_count['total_winners'].sort_values(ascending=False)
max_decade_usa = us_decade_count.loc[us_decade_count['ratio'].idxmax(), 'decade']
max_decade_usa = int(max_decade_usa)
print(max_decade_usa)
us_decade_count.head(15)

2000

    decade  us_winners_count  total_winners     ratio
0   1900.0                 1             57  0.017544
1   1910.0                 3             40  0.075000
2   1920.0                 4             54  0.074074
3   1930.0                14             56  0.250000
4   1940.0                13             43  0.302326
5   1950.0                21             72  0.291667
6   1960.0                21             79  0.265823
7   1970.0                33            104  0.317308
8   1980.0                31             97  0.319588
9   1990.0                42            104  0.403846
10  2000.0                52            123  0.422764
11  2010.0                38            121  0.314050
12  2020.0                18             50  0.360000

In [43]:
fem_winners = nobel_list[nobel_list['sex'] == 'Female'].copy()
fem_winners['category'] = nobel_list['category']
fem_winners = fem_winners.groupby(['decade', 'category']).size().reset_index(name='fem_winners_count')

winners_per_decade = nobel_list.groupby(['decade', 'category']).size().reset_index(name='total_winners')

fem_winners = fem_winners.merge(winners_per_decade, on=['decade', 'category'])

fem_winners['ratio'] = fem_winners['fem_winners_count'] / fem_winners['total_winners']
fem_winners = fem_winners.sort_values('ratio', ascending=False)

# Get the first row of the sorted DataFrame
top_fem = fem_winners.iloc[0]
max_female_dict = {top_fem['decade']: top_fem['category']}
print(max_female_dict)

{2020.0: 'Literature'}

In [44]:
female_winners = nobel_list[nobel_list['sex'] == 'Female'].copy()

top_female_winners = female_winners.iloc[0]
#print(top_female_winners)
first_woman_name = str(top_female_winners['full_name'])
first_woman_category = str(top_female_winners['category'])
#female_winners.head(20)
print(first_woman_name)
print(first_woman_category)

Marie Curie, née Sklodowska
Physics

In [45]:
top_winners_people = nobel_list.value_counts('full_name').reset_index(name='total_prices')
top_winners_people = top_winners_people[top_winners_people['total_prices'] >=2]
print(top_winners_people)
top_winners_organizations = nobel_list.value_counts('organization_name').reset_index(name='total_prices')
top_winners_organizations = top_winners_organizations[top_winners_organizations['total_prices'] >=2]
people_names = top_winners_people['full_name'].tolist()
organization_names = top_winners_organizations['organization_name'].tolist()
repeat_list = people_names
print(repeat_list)

                                           full_name  total_prices
0  Comité international de la Croix Rouge (Intern...             3
1  Office of the United Nations High Commissioner...             2
2                                   Frederick Sanger             2
3                                 Linus Carl Pauling             2
4                                       John Bardeen             2
5                        Marie Curie, née Sklodowska             2
['Comité international de la Croix Rouge (International Committee of the Red Cross)', 'Office of the United Nations High Commissioner for Refugees (UNHCR)', 'Frederick Sanger', 'Linus Carl Pauling', 'John Bardeen', 'Marie Curie, née Sklodowska']